import express from "express";
import { GoogleGenAI } from "@google/genai";
import { guideArticles } from "./data/guidesData";
import { newsArticles } from "./data/newsData";
import dotenv from "dotenv";
import multer from "multer";
import storage from "./lib/storage";
import firestoreAssetHelper from "./lib/firestoreAssetHelper";
import path from "path";
import fs from "fs";
import { promisify } from "util";
const readdir = promisify(fs.readdir);
const stat = promisify(fs.stat);
const readFile = promisify(fs.readFile);
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config();

const app = express();

// Middleware to parse requests
app.use(express.json());
// Serve local assets in dev mode
app.use('/local-assets', express.static(path.resolve(__dirname, '../..', 'resource/assets')));

const upload = multer();

// Presign endpoint - for local mode we will accept a direct upload to server
app.post('/api/assets/presign', async (req, res) => {
  const { key } = req.body;
  if (!key) return res.status(400).json({ error: 'key required' });

  const mode = process.env.STORAGE_MODE || 'local';
  if (mode === 'r2') {
    // Return a presigned PUT URL generated by the r2 adapter
    try {
      const r2 = await import('./lib/storage/r2Adapter');
      const uploadUrl = await r2.getPresignedPutUrl(key);
        const getUrl = await r2.getPresignedGetUrl(key).catch(() => null);
        return res.json({ uploadUrl, getUrl, key });
    } catch (e: any) {
      console.error('Presign r2 error', e?.message || e);
      return res.status(500).json({ error: 'failed to generate presigned url' });
    }
  }

  // For local mode return a server upload proxy
  return res.json({ uploadUrl: `/api/assets/upload?key=${encodeURIComponent(key)}`, key });
});

// Upload proxy for local/dev mode
app.post('/api/assets/upload', upload.single('file'), async (req, res) => {
  try {
    const key = req.query.key as string;
    if (!key) return res.status(400).json({ error: 'key required' });
    const file = (req as any).file;
    if (!file) return res.status(400).json({ error: 'file required' });
    const result = await storage.uploadBuffer(key, file.buffer);
    // try writing metadata to firestore but don't fail the upload if firestore is unavailable
    try {
      await firestoreAssetHelper.createAssetMetadata(key, {
        url: result.url,
        size: result.size,
        contentType: file.mimetype,
        uploadedBy: 'system',
      });
    } catch (e: any) {
      console.warn('firestore createAssetMetadata failed, continuing upload', e?.message || e);
    }
    return res.json({ key, url: result.url });
  } catch (e: any) {
    console.error('Upload error', e);
    return res.status(500).json({ error: e.message });
  }
});

// Complete upload: client calls this after uploading to presigned URL (production) or after proxy upload (local).
app.post('/api/assets/complete', express.json(), async (req, res) => {
  try {
    const { key, size, contentType, hash, uploadedBy } = req.body;
    if (!key) return res.status(400).json({ error: 'key required' });

    const mode = process.env.STORAGE_MODE || 'local';

    // Verify object exists and gather canonical URL depending on storage mode
    let publicUrl: string | null = null;
    let actualSize: number | null = null;

    if (mode === 'r2') {
      const info = await storage.statObject(key);
      if (!info) return res.status(404).json({ error: 'object not found in storage' });
      actualSize = info.size || null;
      if (size && Number(size) !== info.size) {
        console.warn('Size mismatch for', key, { declared: size, actual: info.size });
      }
      publicUrl = await storage.getObjectUrl(key);
    } else {
      // local adapter
      const info = await storage.statObject(key);
      if (!info) return res.status(404).json({ error: 'object not found in local assets' });
      actualSize = info.size || null;
      if (size && Number(size) !== info.size) {
        console.warn('Size mismatch for', key, { declared: size, actual: info.size });
      }
      publicUrl = `/local-assets/${encodeURIComponent(key)}`;
    }

    // Attempt to write metadata to Firestore but do not fail the request if permissions are insufficient
    try {
      await firestoreAssetHelper.createAssetMetadata(key, {
        url: publicUrl,
        size: actualSize,
        contentType: contentType || null,
        hash: hash || null,
        uploadedBy: uploadedBy || 'unknown',
      });
    } catch (e: any) {
      console.warn('firestore createAssetMetadata failed, continuing', e?.message || e);
      return res.json({ ok: true, url: publicUrl });
    }

    return res.json({ ok: true, url: publicUrl });
  } catch (e: any) {
    console.error('Complete upload error', e);
    return res.status(500).json({ error: e.message });
  }
});

// Debug fetch: retrieve object bytes from storage using server credentials (dev-only)
app.get('/api/assets/fetch', async (req, res) => {
  try {
    const key = req.query.key as string;
    if (!key) return res.status(400).json({ error: 'key required' });
    const mode = process.env.STORAGE_MODE || 'local';
    if (mode === 'r2') {
      const r2 = await import('./lib/storage/r2Adapter');
      const { buffer, contentType } = await r2.fetchObjectBuffer(key);
      res.setHeader('Content-Type', contentType);
      res.send(buffer);
      return;
    }
    // local mode — serve from local-assets
    const localPath = path.resolve(__dirname, '../..', 'resource/assets', key);
    return res.sendFile(localPath);
  } catch (e: any) {
    console.error('fetch asset error', e);
    return res.status(500).json({ error: String(e) });
  }
});

// Admin: sync local resource/assets directory to storage (server-side)
app.post('/api/admin/sync-assets', async (req, res) => {
  try {
    const assetsRoot = path.resolve(__dirname, '../..', 'resource/assets');
    const results: { key: string; ok: boolean; error?: string; url?: string }[] = [];

    async function walk(dir: string) {
      const entries = await readdir(dir);
      for (const name of entries) {
        const full = path.join(dir, name);
        const s = await stat(full);
        if (s.isDirectory()) {
          await walk(full);
        } else if (s.isFile()) {
          const rel = path.relative(assetsRoot, full).replace(/\\\\/g, '/');
          try {
            const buf = await readFile(full);
            const contentType = 'application/octet-stream';
            const result = await storage.uploadBuffer(rel, buf, contentType);
            try {
              await firestoreAssetHelper.createAssetMetadata(rel, {
                url: result.url,
                size: result.size,
                contentType,
                uploadedBy: 'admin-sync',
              });
            } catch (e: any) {
              console.warn('firestore createAssetMetadata failed for', rel, e?.message || e);
            }
            results.push({ key: rel, ok: true, url: result.url });
          } catch (e: any) {
            console.error('sync upload error for', rel, e?.message || e);
            results.push({ key: rel, ok: false, error: e?.message || String(e) });
          }
        }
      }
    }

    await walk(assetsRoot);
    return res.json({ ok: true, results });
  } catch (e: any) {
    console.error('sync-assets error', e);
    return res.status(500).json({ error: e?.message || String(e) });
  }
});

// GET endpoint to retrieve guides data from the server
app.get("/api/guides", (req, res) => {
  res.json(guideArticles);
});

// GET endpoint to retrieve news data from the server
app.get("/api/news", (req, res) => {
  res.json(newsArticles);
});

// Lazy initialize Gemini clients
let aiClient: GoogleGenAI | null = null;
function getGeminiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY 环境变量未配置。请在右侧‘Secrets/Settings’面板中配置您的 API Key。");
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// AI Chat endpoint for expert children's ride-on consultation
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, childProfile, lang } = req.body;

    if (!messages || !Array.isArray(messages)) {
      res.status(400).json({ error: "Messages array is required." });
      return;
    }

    const client = getGeminiClient();
    const isEn = lang === "en";

    // Formulate expert advice persona in target language
    let systemInstruction = "";
    if (isEn) {
      systemInstruction = `You are a world-renowned Senior Engineer & Safety Consultant in pediatric rider biomechanics (from the "KIDSMOBI Global Safety Lab").
Your duty is to answer parental inquiries regarding children's ride-on equipment (pedal bikes, balance bikes, push scooters, baby strollers) with extreme rigor, scientific data, objective fairness, and compassionate empathy.

You MUST prioritize the following golden principles of physics, biomechanics, and safety using scientific reasoning:
1. 【Child-to-Bike Weight Ratio】: A kid bicycle's dead weight MUST NOT exceed 30% of the child's body weight (exceeding 40% is equivalent to an adult riding a 60kg motorcycle: it compromises balance, destroys fun, and increases injury risk upon falling). Lightweight frames are vital for safe riding.
2. 【The Coaster Brake Fallacy】: Decidedly caution parents against pedal-back coaster brakes. Coaster brakes freeze the cranks, preventing kids from backpedaling to correct balance at start-off, and lead to asymmetric muscular habits. Recommend narrow, ultra-short reach linear hand brakes (V-brakes/Disc-brakes) customized for tiny toddler hands.
3. 【Riding Geometry】: Q-Factor (bbt bracket width), wheelbase, and stack/reach ratio should position the knee such that it doesn't rise above the navel level, maintaining a low, stable center of gravity.
4. 【Pneumatic vs Solid EVA Tires】: Strongly advocate for pneumatic rubber tires over solid EVA plastic foam because EVA tires have extremely poor friction dampening, causing violent slip-outs and heavy shocks.
5. 【St stroller Spine and Vestibular Protection】: Strollers must support a robust 170°-175° liesflat basket to protect a newborn's delicate spinal posture. Active suspension is critical for dampening retina-shattering road vibrations.

【Target Rider Profile】:
- Age: ${childProfile?.age ? `${childProfile.age} yrs old` : "Unknown"}
- Height / Inseam: ${childProfile?.height ? `${childProfile.height} cm` : "Unknown"} / ${childProfile?.inseam ? `${childProfile.inseam} cm` : "Unknown"}
- Weight: ${childProfile?.weight ? `${childProfile.weight} kg (Max recomm. safe bike weight limit: ${(childProfile.weight * 0.3).toFixed(1)} kg)` : "Unknown"}
- Skill Stage: ${childProfile?.experience || "Unknown"}

Please reply strictly in clear English. Deliver answers formatted in structured, highly scannable Markdown. Use objective scientific data and explain "why", demonstrating absolute integrity, unbiased testing stance, and professional warmth.`;
    } else {
      systemInstruction = `你是一位享誉全球的儿童童车与安全工效学权威资深工程师（来自“KIDSMOBI 全球安全实验室”）。
你的职责是：以极度专业、严谨、客观公正且充满人文关怀的视角，解答家长关于童车（儿童自行车、滑板车、平衡车、婴儿推车）选购和安全标准的疑问。

你在评测和给予决策建议时，必须死守以下行业黄金准则，并用数据、科学原理解释：
1. 【车重黄金比例】：童车重量（尤指自行车）绝不可以超过儿童体重的30%（超过40%等同于让成年人骑一辆60公斤重的摩托。轻量化车架是保护儿童安全与骑行乐趣的关键）。
2. 【刹车制动器认知迷区】：强烈反对手刹不足、仅靠脚踏倒刹（Coaster Brake）的设计。脚踏倒刹会阻碍儿童在起步阶段向后转动脚踏调整平衡，且紧急情况下容易抱死打滑，还会形成长期肌肉代偿；推荐配有极短握距、专为幼童小手定制的线性手刹（V刹、碟刹）。
3. 【骑行几何】：Q-Factor（五通宽度）、Wheelbase（轮距）、和Stack/Reach比，都要保证儿童膝盖不超过肚脐，使发力连贯且重心贴地。
4. 【充气轮胎 vs 发泡轮胎】：平衡车 and 自行车强烈推荐避震与抓地力更好的橡胶充气胎，塑料或发泡EVA轮胎抓地极差，容易打滑倾翻。
5. 【婴儿推车避震与护脊】：推车必须支持170°-175°的睡篮保护新生儿脊椎，四轮弹簧避震是减轻路面颠簸损伤视网膜的重要防护。

【当前咨询儿童档案】（若用户未提供，可提醒用户补充，但必须先基于已知信息作答）：
- 年龄: ${childProfile?.age ? `${childProfile.age} 岁` : "未知"}
- 身高/腿内侧高: ${childProfile?.height ? `${childProfile.height} cm` : "未知"} / ${childProfile?.inseam ? `${childProfile.inseam} cm` : "未知"}
- 体重: ${childProfile?.weight ? `${childProfile.weight} kg (推算最高安全车重 limit: ${(childProfile.weight * 0.3).toFixed(1)} kg)` : "未知"}
- 运动经验: ${childProfile?.experience || "未知"}

请使用清晰的 Markdown 格式输出（简体中文）。用数据说话，解释“为什么”而不是敷衍地说“推荐买”。态度要客观独立（不带有任何商业偏见，坚定的第三方测评立场），同时用词温暖亲切。`;
    }

    // Structure contents for raw generateContent call to gemini-3.5-flash
    const chatContents = messages.map((m: any) => ({
      role: m.role === "user" ? "user" as const : "model" as const,
      parts: [{ text: m.content }],
    }));

    // Helper function to query Gemini with retry and fallback model capability
    const generateWithRetryAndFallback = async (
      ai: GoogleGenAI,
      primaryModel: string,
      contents: any,
      config: any,
      maxRetries = 2
    ) => {
      let lastError: any = null;
      const modelsToTry = [primaryModel, "gemini-3.1-flash-lite"];

      for (const modelName of modelsToTry) {
        for (let attempt = 0; attempt <= maxRetries; attempt++) {
          try {
            console.log(`[AI Chat] Contacting model ${modelName} on attempt ${attempt + 1}/${maxRetries + 1}...`);
            const res = await ai.models.generateContent({
              model: modelName,
              contents,
              config,
            });
            if (res) {
              console.log(`[AI Chat] Successfully received response from ${modelName}`);
              return res;
            }
          } catch (err: any) {
            lastError = err;
            console.warn(`[AI Chat Warning] Attempt ${attempt + 1} of ${modelName} failed:`, err?.message || err);
            
            if (attempt < maxRetries) {
              const delay = Math.pow(2, attempt) * 1000;
              await new Promise((resolve) => setTimeout(resolve, delay));
            }
          }
        }
        console.warn(`[AI Chat Warning] All attempts failed for ${modelName}. Trying next model in fallback list if available...`);
      }
      throw lastError;
    };

    const response = await generateWithRetryAndFallback(
      client,
      "gemini-3.5-flash",
      chatContents,
      {
        systemInstruction,
        temperature: 0.7,
      }
    );

    const replyText = response.text || (isEn ? "Apologies, the safety advisors are currently reviewing. Failed to generate context." : "抱歉，专家顾问正在审查中，未能生成回复。");
    res.json({ reply: replyText });
  } catch (error: any) {
    console.error("Gemini API Error in /api/chat:", error);
    res.status(500).json({
      error: error.message || "服务器遇到未知的 AI 分析配置错误",
      details: "如果您没有配置 GEMINI_API_KEY，请确保在 SECRETS 中正确输入。"
    });
  }
});

export { app };
